Parkeringshus/Parkeringshus/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from main import views

urlpatterns = [
    path('', include('main.urls')),
	path('login/', views.login_request, name="login"),
	path('password-reset/',  auth_views.PasswordResetView.as_view(template_name = 'main/password_reset.html'), name="password_reset"),
	path('password-reset/done/',  auth_views.PasswordResetDoneView.as_view(template_name = 'main/password_reset_done.html'), name="password_reset_done"),
	path('password-reset-confirm/<uidb64>/<token>/',  auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/',  auth_views.PasswordResetCompleteView.as_view(template_name = 'main/password_reset_complete.html'), name="password_reset_complete"),
    path('admin/', admin.site.urls),
]

Parkeringshus/main/urls.py
# urls.py indeholder informationer om hvilket 'view' serveren skal sende til
# browseren når den efterspørger et bestemt URL
from django.urls import path, re_path
# De views som er blevet lavet skal bruges, derfor importeres de
from . import views

app_name = "main"

# URL-mønsteret indstilles. Her refererer det første i path() til underdomænet, det
# andet til hvilken view der skal vises, og hvilket navn det kan refereres til.
urlpatterns = [
	path('', views.homepage, name="homepage"),
	path('total/', views.totalStats, name="totalStats"),
	path('registrer/', views.register, name="registrer"),
	path('logout/', views.logout_request, name="logout"),
	path('support/', views.support, name="login"),
	path('addplate/', views.addplate, name="addplate"),
	re_path('addplate/(?P<pk>\d+)/delete/$', views.deleteplate.as_view(), name="delete_plate"),
]

Parkeringshus/main/models.py
from django.db import models
from datetime import datetime
from django.utils.timezone import utc
from django.core.validators import RegexValidator
import math
import re
from django.core.exceptions import ValidationError

# Create your models here.
valid = [RegexValidator(regex=r"^[A-Z]{2}[0-9]{5}", message='Nummerpladen skal være af formen AT27362 og må ikke indeholde små bogstaver.')]

# kontakt-formular
class Contact(models.Model):
    mail = models.EmailField()
    user = models.CharField(max_length=150)
    subject = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    message = models.TextField()
    file = models.FileField()

# tilføjelse af plader
class Plates(models.Model):
    plateNumber = models.CharField(max_length=7, verbose_name=u"Nummerplade", blank=False, null=False, validators=valid)
    userid = models.IntegerField(default=1)
    state = models.IntegerField(default=0)
    add_date = models.DateTimeField("dato tilføjet", default=datetime.now())

    def __str__(self):
        return self.plateNumber

class Log(models.Model): # log-poster (kørt ind og kørt ud)
    numberplate = models.CharField(max_length=8)
    entered = models.DateTimeField(default=datetime.now())
    exited = models.DateTimeField(default=datetime.now())
    entid = models.IntegerField(default=1)

    def get_time_diff(self): # tid fra kørt ind til kørt ud
        timediffSec = self.exited - self.entered
        timeDiff = timediffSec.total_seconds() / 3600 # Da det er per time, omregnes der fra sekunder til timer
        return math.ceil(timeDiff) # Da det er per påbegyndt time, skal der rundes op.

    def time_till_now(self): # fra kørt ind til nu
        timediffSec = datetime.now - self.entered
        timeDiff = timediffSec.total_seconds() / 3600 # Da det er per time, omregnes der fra sekunder til timer
        return math.ceil(timeDiff) # Da det er per påbegyndt time, skal der rundes op.

class ParkingEntity(models.Model): # de forskellige parkeringshuse
    name = models.CharField(max_length=20,default="")
    available = models.IntegerField(default=500)
    address = models.CharField(max_length=30)
    hourlyRate = models.IntegerField(default=8)
    coords = models.CharField(max_length=100) # til Google Maps-API
    place = models.CharField(max_length=200) # til Google Maps-API

Parkeringshus/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from main.models import Plates
from django.contrib.auth import authenticate, login

# Brugerformularen ændres, så også email er nødvendig
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    # meta bruges til at sige hvad der skal inkluderes
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

# Kontaktformular for anonyme brugere, hvor de skal udfylde email og navn
class ContactFormAnon(forms.Form):
    mail = forms.EmailField(label="Din mailadresse", required=True)
    name = forms.CharField(label="Din navn",required=True)
    subject = forms.CharField(label="Emne",required=True)
    message = forms.CharField(label="Besked", widget=forms.Textarea(attrs={'class' : 'materialize-textarea'}), required=True)
    file = forms.FileField(label="Eventuel fil", required=False)

# brugerkontakt kræver ikke navn og mail, da brugernavnet er givet
class ContactFormUser(forms.Form):
    subject = forms.CharField(label="Emne", required=True)
    message = forms.CharField(label="Besked", widget=forms.Textarea(attrs={'class' : 'materialize-textarea'}), required=True)
    file = forms.FileField(label="Eventuel fil", required=False)

# tilføjelse af nummerplade, hvor kun plateNumber skal udfyldes (resten sker automatisk)
class PlateForm(forms.ModelForm):
    class Meta:
        model = Plates
        fields = ['plateNumber']

Parkeringshus/main/views.py
### Views er det som koder al Django/Python koden (altså modeller og formularer) ###
# sammen med HTML-koden. Det er nødvendigt, da views skaber sammenhæng og giver
# HTML en kontekst, som gør det muligt at bruge Django-funktioner på siderne.
###                                                                              ###

import numpy as np
# Henvisninger til sider
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
# De modeller og formularer som bliver brugt
from .models import Contact, Plates, Log, ParkingEntity
from django.contrib.auth.forms import AuthenticationForm
from .forms import NewUserForm, PlateForm, ContactFormAnon, ContactFormUser
from django.contrib.auth import login, logout, authenticate
from django.views.generic.edit import DeleteView
# Til at vise beskeder, f.eks. når man logger ind
from django.contrib import messages
# Datetime til at holde øje med tiden
from datetime import datetime
#Til at sende emails
from django.core.mail import send_mail, EmailMessage, BadHeaderError
from django.template.loader import render_to_string
#Henter mailadresse fra instillingerne
from django.conf import settings

# Til grafer
import plotly.offline as py
import plotly.graph_objs as go

# Startsiden skal vide om brugeren er logget ind. Hvis det er sandt, så skal den
# supplere meget kontekst, hvilket gøres i render-funktionen.

# Startsiden skal vide om brugeren er logget ind. Hvis det er sandt, så skal
# den vide:
def rm_dups(nums):
    set(tuple(element) for element in nums)
    return [list(t) for t in set(tuple(element) for element in nums)]

def homepage(request):
    current_user = request.user
    uid = current_user.id
    if current_user.is_authenticated:
        return render(request=request,
                      template_name="main/home.html",
                      context={"plates":Plates.objects.filter(userid=uid),
                              "logs":Log.objects.filter(numberplate__in=Plates.objects.
                              filter(userid=uid).values('plateNumber')).order_by('-entered'),
                              "now":datetime.now,"uid":uid,"parkplace":ParkingEntity.objects.all})
    else: return render(request=request,template_name="main/home.html",context=
                        {"parkplace":ParkingEntity.objects.all})

#Funktion til at sende html emails
def send_html_email(to_list, subject, template_name, context, sender=settings.DEFAULT_FROM_EMAIL):
    msg_html = render_to_string(template_name, context)
    msg = EmailMessage(subject=subject, body=msg_html, from_email=sender, bcc=to_list)
    msg.content_subtype = "html"  # Main content is now text/html
    return msg.send()

# registrering
def register(request):
    # hvis brugeren prøver at indsende formularen, da vil det være en POST-request.
    if request.method == "POST":
        # det betyder at en bruger skal oprettes. Der skal benyttes forskellige metoder.
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Kontoen {username} er nu blevet oprettet.")

            #Send velkomsts mail
            template_name="main/velkomstMail.html"
            to_list = [form.cleaned_data.get('email')]
            subject = "Velkommen til Parkering.tk"
            context = {'username': username}
            send_html_email(to_list, subject, template_name, context, sender=settings.DEFAULT_FROM_EMAIL)

            # brugeren bliver logget ind
            login(request, user)
            messages.info(request, f"Du er nu logget ind med {username}.")
            return redirect("main:homepage")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")
            return render(request = request,
                          template_name = "main/register.html",
                          context={"form":form})
    form = NewUserForm
    return render(request,
                  "main/register.html",
                  context={"form":form})

# Når en bruger prøver at logge ud
def logout_request(request):
    logout(request)
    messages.info(request, "Du er nu logget ud.")
    return redirect("main:homepage")

# Når en bruger prøver at logge ind
def login_request(request):
    # Igen er der tale om en form, så det skal være en POST-request
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            # Brugeren skal autenciteres gennem brugernavn og adgangskode
            user = authenticate(username=username, password=password)
            if user is not None:
                # Findes brugeren skal brugeren logges ind, og en info-besked
                # skal fortælle at man er logget ind og omdirigeres til brugersiden
                login(request, user)
                messages.info(request, f"Du er nu logget på som {username}")
                return redirect('main:homepage')
            else:
                messages.error(request, "Brugernavn og adgangskode passer ikke.")
        else:
            messages.error(request, "Brugernavn og adgangskode passer ikke.")
    form = AuthenticationForm()
    return render(request = request,
                    template_name = "main/login.html",
                    context={"form":form})

# Support-siden har to forskellige tilfælde
def support(request):
    current_user = request.user
    # er det en GET-request skal det blot vises
    if request.method == 'GET':
        # Brugeren er logget ind
        if current_user.is_authenticated:
            form = ContactFormUser
        # Brugeren er ikke logget ind
        else:
            form = ContactFormAnon()
    # Ellers må det være en POST-request, som så betyder at formularen er udfyldt
    else:
        if current_user.is_authenticated:
            form = ContactFormUser(request.POST)
            if form.is_valid():
                # Hvis formularen er gyldig skal data 'renses' – da det ellers
                # er i en dictionary med alle mulige værdier
                subject = form.cleaned_data['subject']
                message = form.cleaned_data['message']
                input = "Fra: {}\nEmne: {}\nBesked:\n{}\nSendt {}".format(current_user.id,subject,message,datetime.now())
                try:
                    send_mail("Ny besked: " + subject, input, str(current_user.id)+"@parkering.tk", ['parkeringtk@gmail.com'])
                except BadHeaderError:
                    return HttpResponse('Invalid header found.')
        else:
            form = ContactFormAnon(request.POST)
            if form.is_valid():
                subject = form.cleaned_data['subject']
                message = form.cleaned_data['message']
                name = form.cleaned_data['name']
                from_mail = form.cleaned_data['mail']
                input = "Fra mail: {}\nNavn: {}\nEmne: {}\nBesked:\n{}\nSendt {}".format(from_mail,name,subject,message,datetime.now())
                try:
                    send_mail(subject, input, from_mail, ['parkeringtk@gmail.com'])
                except BadHeaderError:
                    return HttpResponse('Invalid header found.')

        return redirect('/support')
        messages.success(request, f"Din besked er blevet sendt.")
    return render(request, "main/support.html", {'form': form})


def addplate(request):
    current_user = request.user
    form = PlateForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            plateNumber = form.cleaned_data.get('plateNumber')
            newPlate = Plates(plateNumber=plateNumber, userid=current_user.id, state=1, add_date=datetime.now())
            newPlate.save()
            messages.info(request, f"Nummerpladen {plateNumber} afventer nu godkendelse.")
            return redirect('main:addplate')
        else:
            messages.error(request, f"Der var noget galt med den indtastede nummerplade, prøv igen.")

    return render(request = request,
                  template_name = "main/addplate.html",
                  context={"form":form,"plates":Plates.objects.all,"uid":current_user.id})

def totalStats(request):
    current_user = request.user
    uid = current_user.id
    if current_user.is_authenticated:
        # De to QuerySet initialiseres
        logs = Log.objects.filter(numberplate__in=Plates.objects.filter(userid=uid).values('plateNumber'),exited__isnull=False).order_by('exited')
        parkplace = ParkingEntity.objects.all()
        # Variable og lister initialiseres
        total = 0
        hours = 0

        x = []
        y1 = []
        y1change = []
        y2 = []
        y2change = []
        for log in logs:
            for house in parkplace:
                if house.id == log.entid:
                    hourlyRate = house.hourlyRate
            duration = log.get_time_diff()
            subtotal = duration * hourlyRate

            # Først adderes det
            hours += duration
            total += subtotal
            # Herefter tilføjes det til et array
            x.append(log.exited)
            y1.append(hours)
            y1change.append(duration)
            y2.append(total)
            y2change.append(subtotal)

        trace_duration = go.Scatter(
            x=x,
            y=y1,
            name = "Varighed",
            line = dict(color = '#17BECF'),
            opacity = 0.8,
            hoverinfo = 'name+y')

        trace_duration_change = go.Bar(
            x=x,
            y=y1change,
            name = "Varighed",
            marker=dict(
                color='#17BECF',
                line=dict(
                    color='#17BECF',
                    width=1.5,

Parkeringshus/main/templates/main/addplate.html
{% extends 'main/header.html' %}

{% block content %} <!-- bliver inkluderet i header.html -->
  <br><br><br>
  <ul class="collapsible">
  <!-- vises kun for dem som er logget ind -->
  {% if user.is_authenticated %}
    {% for plate in plates %}
      {% if plate.userid == uid %}
      <!-- laves i collapsible-form, så brugeren kan udvide elementerne -->
        {% if plate.state == 0 %}
        <!-- hvis nummerpladen er bekræfter har den 0-status, hvilket vises med -->
          <li>
            <div class="collapsible-header"><i class="material-icons">done</i><b>Bekræftet</b>: {{plate.plateNumber}}</div>
            <div class="collapsible-body"><span>Tilføjet: {{plate.add_date}}<br>Historik: <a href="/">tryk her</a></span></div>
          </li>
        {% elif plate.state == 1 %}
        <!-- hvis nummerpladen ikke er begrænset skal den vises på en anden måde - derudover skal der være mulighed for
        at slette nummerpladen (kan også gøres ved at skrive til support), hvilket gøres gennem en formular -->
          <li>
            <div class="collapsible-header"><i class="material-icons">loop</i><em>Afventer</em>: {{plate.plateNumber}}</div>
            <div class="collapsible-body"><span><em>Godkendelse afventer</em><br>Tilføjet: {{plate.add_date}}<br><br>
            <form action="{% url 'main:delete_plate' pk=plate.id %}" method="post" style="display: inline;">
              {% csrf_token %}
              <input type="hidden" name="plate_id" value="{{ plate.id }}" />
              <button class="btn waves-effect waves-light" type="submit" name="action">Slet<i class="material-icons right">delete_outline</i>  </button>
            </form>
          </li>
        {% endif %}
      {% endif %}
    {% endfor %}
  </ul>

    <!-- Kør for alle: mulighed for at tilføje nye nummerplader-->
    <div class="row">
      <div class="col offset-l2 s12">
        <div class="row">
          <form class="col s12" method="POST">
            {% csrf_token %}
            <div class="input-field col s6">
            {{form.as_p}}
            </div>
            <div class="input-field col s2">
             <p class="center-align"><button class="btn waves-effect waves-light" type="submit" name="action">Tilføj<i class="material-icons right">add</i></button></p>
            </div>
          </form>
        </div>
      </div>
    </div>


  {% else %}
    <div class="row">
      <div class="col offset-l3 s12 m6">
        <div class="card red darken-1">
          <div class="card-content white-text">
            <span class="card-title">Adgang nægtet!</span>
            <p>Da du ikke er logget ind, har du ikke mulighed for at ændre og tilføje nummerplader.</p>
          </div>
          <div class="card-action">
            <a href="/">Startside</a>
            <a href="/login">Log ind</a>
          </div>
        </div>
      </div>
    </div>
  {% endif %}

{% endblock %}

Parkeringshus/main/templates/main/header.html
<head> <!-- indikerer først at der skal indlæses statisk indhold -->
  {% load static %}
  <!--Import Google Icon Font-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- Compiled and minified CSS -->
  <link href="{% static 'main/css/materialize.css' %}" rel="stylesheet">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <!-- Cookie-information og GDPR-compliance -->
  <link rel="stylesheet" type="text/css" src="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <title>Parkering.tk – Parkeringshuse</title>
  <script>
      $(document).ready(function(){
        $(".dropdown-trigger").dropdown();
      });
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.sidenav');
        var instances = M.Sidenav.init(elems, {});
      });
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.dropdown-trigger');
        var instances = M.Dropdown.init(elems, {coverTrigger: false});
      });
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.fixed-action-btn');
        var instances = M.FloatingActionButton.init(elems, {});
      });
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.tooltipped');
        var instances = M.Tooltip.init(elems, {});
      });
      document.addEventListener('DOMContentLoaded', function() {
          var elems = document.querySelectorAll('.sidenav');
          var instances = M.Sidenav.init(elems, {});
      });
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.collapsible');
        var instances = M.Collapsible.init(elems, {});
      });
  </script>
</head>

<body> <!-- navbar og beskeder går forud for header -->
  {% include "main/includes/navbar.html" %}
  {% include "main/includes/messages.html" %}
  <div class="container">
    {% block content %}
    <!-- heri bliver al indhold fra de øvrige sider inkluderet -->
    {% endblock %}
  </div>
  {% if user.is_authenticated %}
    <div class="fixed-action-btn">
      <a class="btn-floating btn-large red">
        <i class="large material-icons">menu</i>
      </a>
      <ul>
        <li><a class="btn-floating yellow darken-1 tooltipped" data-position="left" data-tooltip="Support" href="/support"><i class="material-icons">message</i></a></li>
        <li><a class="btn-floating green tooltipped" data-position="left" data-tooltip="Total & statistik" href="/total"><i class="material-icons">account_balance_wallet</i></a></li>
        <li><a class="btn-floating blue tooltipped" data-position="left" data-tooltip="Tilføj nummerplade" href="/addplate"><i class="material-icons">add</i></a></li>
      </ul>
    </div>
  {% endif %}
  <br>
  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l3 s12">
          <h5 class="white-text">Om Parkering ApS</h5>
          <p class="grey-text text-lighten-4">I samarbejde med forskellige storcentrer arbejder vi for at gøre parkeringen nemmere for kunderne.</p>
        </div>
        <div class="col l2 offset-l1 s12">
          <h5 class="white-text">Kontakt</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="/support"><b>Kontakt support</b></a></li>
            <li><a class="grey-text text-lighten-3" href="mailto:service@parkering.tk"><b>Mail:</b><br>service@parkering.tk</a></li>
            <li><a class="grey-text text-lighten-3"><b>Telefon:</b><br>+45 82837482</a></li>
          </ul>
        </div>
        <div class="col l2 offset-l1 s12">
          <h5 class="white-text">Diverse</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Pressekontakt</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Partnere</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Brugsbetingelser</a></li>
            <li><a class="grey-text text-lighten-3" href="/support#omhandler=Betaling-titel=Dispensation">Dispensation</a></li>
          </ul>
        </div>
        <div class="col l2 offset-l1 s12">
          <h5 class="white-text">Social</h5>
          <ul>
            <p class="grey-text text-lighten-4">Sociale ikoner og links</p>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2019 Parkerings ApS — Alle rettigheder forbeholdes
      </div>
    </div>
  </footer>
</body>

Parkeringshus/main/templates/main/home.html
{% extends 'main/header.html' %}

{% block content %}
  {% if user.is_authenticated %}
    {% include "main/includes/brugerside.html" %}
  {% else %}
    {% include "main/includes/startside.html" %}
  {% endif %}
{% endblock %}

Parkeringshus/main/templates/main/login.html
{% extends 'main/header.html' %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <br>
    <button class="btn" style="background-color=yellow; color=blue" type="submit">Log ind</button>
  </form>
  Har du ikke i forvejen en konto, <a href="/registrer">kan du <b>oprette dig her</b></a>.
  Har du glemt din adgangskode, <a href="/password-reset">kan du <b>få en ny her</b></a>.
{% endblock %}

Parkeringshus/main/templates/main/password_reset.html
{% extends 'main/header.html' %}
<!-- Siden som man kommer hen på for at nulstille sit password -->
{% block content %}
<div class="content-section">
        <form method="POST">
            {% csrf_token %} <!-- token identificeres, for at godkende formularens integritet -->
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Nulstil Password</legend>
                {{form.as_p}} <!-- formularen 'printes' i paragraf-form, så det er inddelt i afsnit -->
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Anmod om link til nulstilling af password</button>
            </div>
        </form>
</div>
{% endblock %}

Parkeringshus/main/templates/main/password_reset_complete.html
{% extends 'main/header.html' %}

{% block content %}
<div class="alert alert-info">
       Dit password er nu blevet nulstillet.
</div>
 <a href="{% url 'login' %}">Login her</a>
{% endblock %}

Parkeringshus/main/templates/main/password_reset_confirm.html
{% extends 'main/header.html' %}
{% block content %}
<div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                  {{form.as_p}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
</div>
{% endblock %}

Parkeringshus/main/templates/main/password_reset_done.html
{% extends 'main/header.html' %}

{% block content %}
<div class="alert alert-info">
  Der er nu blevet sendt en email med instruktioner omkring nulstilling af dit password.
</div>
{% endblock %}

Parkeringshus/main/templates/main/register.html
{% extends 'main/header.html' %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <br>
    <button class="btn" style type="submit">Registrer</button>
  </form>
  Har du allerede en konto, <a href="/login">kan du <strong>logge ind her</strong>.</a>
{% endblock %}

Parkeringshus/main/templates/main/support.html
{% extends 'main/header.html' %}

{% block content %}
  <br>
  <div class="row">
    <div class="col s12">
      <div class="col m10 offset-m1 s12">
          <h2 class="center-align">Kontakt</h2>
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="form-actions">
              <p class="center-align"><button class="btn waves-effect waves-light" type="submit" name="action">Indsend<i class="material-icons right">send</i></button></p>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

Parkeringshus/main/templates/main/total.html
{% extends 'main/header.html' %}
{% load app_filters %}{% load humanize %}
{% block content %}
<br><br> <!-- først repræsenteret det i listeform -->
  {% if logs.count > 0 %} <!-- Hvis brugeren har tidligere historik (derved også nummerplade) -->
    <h2>I alt</h2>
      <table>
        <thead>
          <tr>
              <th>Total varighed</th>
              <th>Totalt beløb</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>{{hours}} timer</td>
            <td>{{total}} kroner</td>
          </tr>
        </tbody>
      </table>

    <h3>Statistik</h3>
    <h4>Totale beløb og varighed</h4>
    {% if graph1 %} <!-- er grafen defineret, da skal den vises -->
      <div>
      {{ graph1|safe }} <!-- før den kan blive vist skal der indikeres at der
        er tale om sikkert indhold, eller stoler template ikke på det -->
      </div>
    {% endif %}
    <h4>Ændringen i beløb og varighed</h4>
    {% if graph2 %}
      <div>
      {{ graph2|safe }}
      </div>
    {% endif %}
  {% else %}
    Du har endnu ikke brugt din nummerplade i et parkeringshus.
  {% endif %}
  {{dat}}
{% endblock %}

Parkeringshus/main/templates/main/velkomstMail.html
<html>
    <head>
    </head>
    <body>
        <h1>Hej {{username}}, velkommen til Parkering.tk!</h1>
        <h3>Du er nu klar til at tilføje din nummerplade på hjemmesiden, og derefter besøge en af vores parkeringshuse.</h3>
        <a href="http://parkering.tk/addplate" style="background-color:#EB7035;border:1px solid #EB7035;border-radius:3px;color:#ffffff;display:inline-block;font-family:sans-serif;font-size:16px;line-height:44px;text-align:center;text-decoration:none;width:400px;-webkit-text-size-adjust:none;mso-hide:all;">Klik her for at tilføje din nummerplade</a>
        <div class="slider">
          <img src="https://img.autoplus.fr/news/2017/11/20/1522328/1350|900|721f1ad4d6eeb70a6ec1e7bd.jpg?r" width="450" height="300">
            <div class="valign caption left-align">
              <h1 class="light blue-text"><b>Bekymringsfri parkering</b></h1>
              <h5 class="light grey-text text-lighten-3"><b>Med Parkering.tk er det pludselig nemt og hurtigt at parkere.</b></h5>
          </div>
        </div>
    </body>
</html>